import { Product } from "@/types/products";

const data: Product[] = [
  // ── A01 客服资源 ─────────────────────────────
  {
    id: "A011",
    title: "客服培训手册",
    desc: "从行业认知到岗位技能的系统化培训手册",
    price: "¥19.99",
    images: ["/images/products/product-1.jpeg", "/images/products/product-1-hover.jpeg"],
    img1: "/images/products/product-1.jpeg",
    img2: "/images/products/product-1-hover.jpeg",
    link: "/category/ecomats/A011",
    category: "客服资源",
    details: { fileType: "PDF + Word", fileSize: "2.3 MB", format: "电子文档" },
    rating: 4.8,
    reviewCount: 126,
  },
  {
    id: "A012",
    title: "客服话术大全",
    desc: "售前/售后/催付等全场景话术模板",
    price: "¥18.99",
    images: ["/images/products/product-2.jpeg", "/images/products/product-2-hover.jpeg"],
    img1: "/images/products/product-2.jpeg",
    img2: "/images/products/product-2-hover.jpeg",
    link: "/category/ecomats/A012",
    category: "客服资源",
    details: { fileType: "PDF + Word", fileSize: "1.8 MB", format: "电子文档" },
    rating: 4.7,
    reviewCount: 98,
  },
  {
    id: "A014",
    title: "客服主管实战指南",
    desc: "团队管理/绩效考评/数据复盘全攻略",
    price: "¥24.99",
    images: ["/images/products/product-3.jpeg", "/images/products/product-3-hover.jpeg"],
    img1: "/images/products/product-3.jpeg",
    img2: "/images/products/product-3-hover.jpeg",
    link: "/category/ecomats/A014",
    category: "客服资源",
    details: { fileType: "PDF + Excel", fileSize: "3.5 MB", format: "电子文档" },
    rating: 4.9,
    reviewCount: 203,
  },
  {
    id: "A015",
    title: "客服流程SOP标准",
    desc: "咨询-下单-售后全链路标准化操作流程",
    price: "¥14.99",
    images: ["/images/products/product-4.jpeg", "/images/products/product-4-hover.jpeg"],
    img1: "/images/products/product-4.jpeg",
    img2: "/images/products/product-4-hover.jpeg",
    link: "/category/ecomats/A015",
    category: "客服资源",
    details: { fileType: "Excel + Word", fileSize: "1.2 MB", format: "表格文档" },
    rating: 4.6,
    reviewCount: 87,
  },
  {
    id: "A01P",
    title: "客服资源全套资料包",
    desc: "培训手册+话术大全+主管指南+流程SOP合集",
    price: "¥49.99",
    images: ["/images/products/product-5.jpeg", "/images/products/product-5-hover.jpeg"],
    img1: "/images/products/product-5.jpeg",
    img2: "/images/products/product-5-hover.jpeg",
    link: "/category/ecomats/A01P",
    category: "客服资源",
    details: { fileType: "综合资料包", fileSize: "8.8 MB", format: "全套合集" },
    rating: 5.0,
    reviewCount: 312,
  },

  // ── B01 运营资源 ─────────────────────────────
  {
    id: "B011",
    title: "店铺运营体系搭建",
    desc: "从0到1搭建标准化店铺运营体系",
    price: "¥29.99",
    images: ["/images/products/product-6.jpeg", "/images/products/product-6-hover.jpeg"],
    img1: "/images/products/product-6.jpeg",
    img2: "/images/products/product-6-hover.jpeg",
    link: "/category/ecomats/B011",
    category: "运营资源",
    details: { fileType: "PDF + Excel", fileSize: "4.2 MB", format: "电子文档" },
    rating: 4.8,
    reviewCount: 189,
  },
  {
    id: "B012",
    title: "爆款打造体系",
    desc: "选品-测款-推广-维护全流程爆款方法论",
    price: "¥34.99",
    images: ["/images/products/product-7.jpeg", "/images/products/product-7-hover.jpeg"],
    img1: "/images/products/product-7.jpeg",
    img2: "/images/products/product-7-hover.jpeg",
    link: "/category/ecomats/B012",
    category: "运营资源",
    details: { fileType: "PDF + PPT", fileSize: "6.5 MB", format: "电子文档" },
    rating: 4.9,
    reviewCount: 234,
  },
  {
    id: "B013",
    title: "货品管理体系",
    desc: "商品分层/库存管理/上新策略一站式方案",
    price: "¥22.99",
    images: ["/images/products/product-8.jpeg", "/images/products/product-8-hover.jpeg"],
    img1: "/images/products/product-8.jpeg",
    img2: "/images/products/product-8-hover.jpeg",
    link: "/category/ecomats/B013",
    category: "运营资源",
    details: { fileType: "Excel + PDF", fileSize: "3.1 MB", format: "表格工具" },
    rating: 4.7,
    reviewCount: 156,
  },
  {
    id: "B014",
    title: "私域运营体系",
    desc: "企微社群/朋友圈/会员体系全链路运营",
    price: "¥26.99",
    images: ["/images/products/product-9.jpeg", "/images/products/product-9-hover.jpeg"],
    img1: "/images/products/product-9.jpeg",
    img2: "/images/products/product-9-hover.jpeg",
    link: "/category/ecomats/B014",
    category: "运营资源",
    details: { fileType: "PDF + Word", fileSize: "4.0 MB", format: "电子文档" },
    rating: 4.6,
    reviewCount: 134,
  },
  {
    id: "B01P",
    title: "运营资源全套资料包",
    desc: "店铺运营+爆款打造+货品管理+私域运营合集",
    price: "¥59.99",
    images: ["/images/products/product-10.jpeg", "/images/products/product-10-hover.jpeg"],
    img1: "/images/products/product-10.jpeg",
    img2: "/images/products/product-10-hover.jpeg",
    link: "/category/ecomats/B01P",
    category: "运营资源",
    details: { fileType: "综合资料包", fileSize: "17.8 MB", format: "全套合集" },
    rating: 5.0,
    reviewCount: 287,
  },
];

export const allProducts: Product[] = data;
export const productsMap: Record<string, Product[]> = {};
export const defaultSectionTitles: string[] = [];
