import { Product } from "@/types/products";

const data: Product[] = [
  // ── C01 简历优化 ─────────────────────────────
  {
    id: "C011",
    title: "电商简历模板精选集",
    desc: "10份精美简历模板+撰写技巧",
    price: "¥9.99",
    images: ["/images/products/product-1.jpeg", "/images/products/product-1-hover.jpeg"],
    img1: "/images/products/product-1.jpeg",
    img2: "/images/products/product-1-hover.jpeg",
    link: "/category/jobtips/C011",
    category: "简历优化",
    details: { fileType: "Word + PDF", fileSize: "3.2 MB", format: "简历模板" },
    rating: 4.6,
    reviewCount: 201,
  },
  {
    id: "C012",
    title: "简历自我评价范文库",
    desc: "200+岗位自我评价范文直接套用",
    price: "¥6.99",
    images: ["/images/products/product-2.jpeg", "/images/products/product-2-hover.jpeg"],
    img1: "/images/products/product-2.jpeg",
    img2: "/images/products/product-2-hover.jpeg",
    link: "/category/jobtips/C012",
    category: "简历优化",
    details: { fileType: "Word", fileSize: "1.5 MB", format: "范文集合" },
    rating: 4.5,
    reviewCount: 167,
  },
  {
    id: "C014",
    title: "简历项目经验写法",
    desc: "突出数据成果与个人贡献的项目描述技巧",
    price: "¥11.99",
    images: ["/images/products/product-3.jpeg", "/images/products/product-3-hover.jpeg"],
    img1: "/images/products/product-3.jpeg",
    img2: "/images/products/product-3-hover.jpeg",
    link: "/category/jobtips/C014",
    category: "简历优化",
    details: { fileType: "PDF + Word", fileSize: "1.8 MB", format: "电子文档" },
    rating: 4.7,
    reviewCount: 89,
  },
  {
    id: "C015",
    title: "简历投递策略指南",
    desc: "精准投递+跟进技巧+面试邀约率提升",
    price: "¥8.99",
    images: ["/images/products/product-4.jpeg", "/images/products/product-4-hover.jpeg"],
    img1: "/images/products/product-4.jpeg",
    img2: "/images/products/product-4-hover.jpeg",
    link: "/category/jobtips/C015",
    category: "简历优化",
    details: { fileType: "PDF", fileSize: "0.9 MB", format: "电子文档" },
    rating: 4.4,
    reviewCount: 73,
  },
  {
    id: "C01P",
    title: "简历优化全套资料包",
    desc: "模板精选+范文库+项目写法+投递策略合集",
    price: "¥24.99",
    images: ["/images/products/product-5.jpeg", "/images/products/product-5-hover.jpeg"],
    img1: "/images/products/product-5.jpeg",
    img2: "/images/products/product-5-hover.jpeg",
    link: "/category/jobtips/C01P",
    category: "简历优化",
    details: { fileType: "综合资料包", fileSize: "7.4 MB", format: "全套合集" },
    rating: 4.9,
    reviewCount: 223,
  },

  // ── D01 面试技巧 ─────────────────────────────
  {
    id: "D011",
    title: "面试自我介绍模板",
    desc: "30个常见面试问题及满分回答",
    price: "¥12.99",
    images: ["/images/products/product-6.jpeg", "/images/products/product-6-hover.jpeg"],
    img1: "/images/products/product-6.jpeg",
    img2: "/images/products/product-6-hover.jpeg",
    link: "/category/jobtips/D011",
    category: "面试技巧",
    details: { fileType: "PDF + MP3", fileSize: "45 MB", format: "音频+文档" },
    rating: 4.7,
    reviewCount: 89,
  },
  {
    id: "D012",
    title: "行为面试STAR法则",
    desc: "无领导小组+压力面试通关方法",
    price: "¥15.99",
    images: ["/images/products/product-7.jpeg", "/images/products/product-7-hover.jpeg"],
    img1: "/images/products/product-7.jpeg",
    img2: "/images/products/product-7-hover.jpeg",
    link: "/category/jobtips/D012",
    category: "面试技巧",
    details: { fileType: "PDF + Word", fileSize: "1.5 MB", format: "电子文档" },
    rating: 4.5,
    reviewCount: 56,
  },
  {
    id: "D013",
    title: "薪资谈判技巧话术",
    desc: "高情商提加薪的完整话术方案",
    price: "¥13.99",
    images: ["/images/products/product-8.jpeg", "/images/products/product-8-hover.jpeg"],
    img1: "/images/products/product-8.jpeg",
    img2: "/images/products/product-8-hover.jpeg",
    link: "/category/jobtips/D013",
    category: "面试技巧",
    details: { fileType: "PDF + MP3", fileSize: "35 MB", format: "音频+文档" },
    rating: 4.9,
    reviewCount: 223,
  },
  {
    id: "D014",
    title: "面试常见问题应答",
    desc: "从简历到终面的完整面试流程",
    price: "¥19.99",
    images: ["/images/products/product-9.jpeg", "/images/products/product-9-hover.jpeg"],
    img1: "/images/products/product-9.jpeg",
    img2: "/images/products/product-9-hover.jpeg",
    link: "/category/jobtips/D014",
    category: "面试技巧",
    details: { fileType: "PDF + PPT", fileSize: "8.3 MB", format: "电子文档" },
    rating: 4.8,
    reviewCount: 134,
  },
  {
    id: "D01P",
    title: "面试技巧全套资料包",
    desc: "自我介绍+STAR法则+薪资谈判+常见问答合集",
    price: "¥39.99",
    images: ["/images/products/product-10.jpeg", "/images/products/product-10-hover.jpeg"],
    img1: "/images/products/product-10.jpeg",
    img2: "/images/products/product-10-hover.jpeg",
    link: "/category/jobtips/D01P",
    category: "面试技巧",
    details: { fileType: "综合资料包", fileSize: "89.8 MB", format: "全套合集" },
    rating: 5.0,
    reviewCount: 312,
  },
];

export const allProducts: Product[] = data;
export const productsMap: Record<string, Product[]> = {};
export const defaultSectionTitles: string[] = [];
